"""initial schema

Revision ID: fe25e6d2a7ad
Revises:
Create Date: 2025-12-12 14:21:48.754000

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fe25e6d2a7ad"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # Defer foreign key checks for SQLite to handle circular dependencies
    # supervisory_orgs.manager_worker_id -> workers.worker_id
    # positions.worker_id -> workers.worker_id
    # workers table is created after these tables, so we need to defer FK checks
    connection = op.get_bind()
    if "sqlite" in str(connection.engine.url):
        connection.execute(sa.text("PRAGMA defer_foreign_keys=ON"))

    # ### commands auto generated by Alembic - please adjust! ###
    # Create tables without foreign key dependencies first
    op.create_table(
        "job_profiles",
        sa.Column("job_profile_id", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("job_family", sa.String(), nullable=False),
        sa.Column("job_level", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("job_profile_id"),
    )
    op.create_table(
        "locations",
        sa.Column("location_id", sa.String(), nullable=False),
        sa.Column("location_name", sa.String(), nullable=False),
        sa.Column("city", sa.String(), nullable=True),
        sa.Column("country", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("location_id"),
    )
    # supervisory_orgs has self-referencing FKs (nullable), so create it next
    op.create_table(
        "supervisory_orgs",
        sa.Column("org_id", sa.String(), nullable=False),
        sa.Column("org_name", sa.String(), nullable=False),
        sa.Column("org_type", sa.String(), nullable=False),
        sa.Column("parent_org_id", sa.String(), nullable=True),
        sa.Column("manager_worker_id", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "org_type IN ('Supervisory', 'Cost_Center', 'Location')", name="check_org_type"
        ),
        sa.ForeignKeyConstraint(
            ["manager_worker_id"],
            ["workers.worker_id"],
        ),
        sa.ForeignKeyConstraint(
            ["parent_org_id"],
            ["supervisory_orgs.org_id"],
        ),
        sa.PrimaryKeyConstraint("org_id"),
    )
    # cost_centers depends on supervisory_orgs
    op.create_table(
        "cost_centers",
        sa.Column("cost_center_id", sa.String(), nullable=False),
        sa.Column("cost_center_name", sa.String(), nullable=False),
        sa.Column("org_id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["supervisory_orgs.org_id"],
        ),
        sa.PrimaryKeyConstraint("cost_center_id"),
    )
    # positions depends on job_profiles and supervisory_orgs (worker_id FK is nullable)
    op.create_table(
        "positions",
        sa.Column("position_id", sa.String(), nullable=False),
        sa.Column("job_profile_id", sa.String(), nullable=False),
        sa.Column("org_id", sa.String(), nullable=False),
        sa.Column("fte", sa.Float(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("worker_id", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint("status IN ('open', 'filled', 'closed')", name="check_position_status"),
        sa.CheckConstraint("fte >= 0.0 AND fte <= 1.0", name="check_fte_range"),
        sa.ForeignKeyConstraint(
            ["job_profile_id"],
            ["job_profiles.job_profile_id"],
        ),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["supervisory_orgs.org_id"],
        ),
        sa.ForeignKeyConstraint(
            ["worker_id"],
            ["workers.worker_id"],
        ),
        sa.PrimaryKeyConstraint("position_id"),
    )
    op.create_table(
        "workers",
        sa.Column("worker_id", sa.String(), nullable=False),
        sa.Column("job_profile_id", sa.String(), nullable=False),
        sa.Column("org_id", sa.String(), nullable=False),
        sa.Column("cost_center_id", sa.String(), nullable=False),
        sa.Column("location_id", sa.String(), nullable=True),
        sa.Column("position_id", sa.String(), nullable=True),
        sa.Column("employment_status", sa.String(), nullable=False),
        sa.Column("fte", sa.Float(), nullable=False),
        sa.Column("hire_date", sa.String(), nullable=False),
        sa.Column("termination_date", sa.String(), nullable=True),
        sa.Column("effective_date", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "employment_status IN ('Active', 'Terminated', 'Leave')", name="check_employment_status"
        ),
        sa.CheckConstraint("fte >= 0.0 AND fte <= 1.0", name="check_worker_fte"),
        sa.ForeignKeyConstraint(
            ["cost_center_id"],
            ["cost_centers.cost_center_id"],
        ),
        sa.ForeignKeyConstraint(
            ["job_profile_id"],
            ["job_profiles.job_profile_id"],
        ),
        sa.ForeignKeyConstraint(
            ["location_id"],
            ["locations.location_id"],
        ),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["supervisory_orgs.org_id"],
        ),
        sa.ForeignKeyConstraint(
            ["position_id"],
            ["positions.position_id"],
        ),
        sa.PrimaryKeyConstraint("worker_id"),
    )
    op.create_table(
        "movements",
        sa.Column("event_id", sa.String(), nullable=False),
        sa.Column("worker_id", sa.String(), nullable=False),
        sa.Column("event_type", sa.String(), nullable=False),
        sa.Column("event_date", sa.String(), nullable=False),
        sa.Column("from_org_id", sa.String(), nullable=True),
        sa.Column("to_org_id", sa.String(), nullable=True),
        sa.Column("from_cost_center_id", sa.String(), nullable=True),
        sa.Column("to_cost_center_id", sa.String(), nullable=True),
        sa.Column("from_job_profile_id", sa.String(), nullable=True),
        sa.Column("to_job_profile_id", sa.String(), nullable=True),
        sa.Column("from_position_id", sa.String(), nullable=True),
        sa.Column("to_position_id", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "event_type IN ('hire', 'termination', 'transfer')", name="check_event_type"
        ),
        sa.ForeignKeyConstraint(
            ["from_cost_center_id"],
            ["cost_centers.cost_center_id"],
        ),
        sa.ForeignKeyConstraint(
            ["from_job_profile_id"],
            ["job_profiles.job_profile_id"],
        ),
        sa.ForeignKeyConstraint(
            ["from_org_id"],
            ["supervisory_orgs.org_id"],
        ),
        sa.ForeignKeyConstraint(
            ["to_cost_center_id"],
            ["cost_centers.cost_center_id"],
        ),
        sa.ForeignKeyConstraint(
            ["to_job_profile_id"],
            ["job_profiles.job_profile_id"],
        ),
        sa.ForeignKeyConstraint(
            ["to_org_id"],
            ["supervisory_orgs.org_id"],
        ),
        sa.ForeignKeyConstraint(
            ["worker_id"],
            ["workers.worker_id"],
        ),
        sa.PrimaryKeyConstraint("event_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop tables in reverse order of creation
    op.drop_table("movements")
    op.drop_table("workers")
    op.drop_table("positions")
    op.drop_table("cost_centers")
    op.drop_table("supervisory_orgs")
    op.drop_table("locations")
    op.drop_table("job_profiles")
    # ### end Alembic commands ###
