"""Initial migration with all models

Revision ID: 191f11dc3b4d
Revises:
Create Date: 2025-11-07 07:32:02.092320

"""

from alembic import op
from sqlalchemy import (
    Column,
    DateTime,
    ForeignKeyConstraint,
    PrimaryKeyConstraint,
    String,
    Text,
    UniqueConstraint,
)

# revision identifiers, used by Alembic.
revision = "191f11dc3b4d"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "groups",
        Column("id", String(length=36), nullable=False),
        Column("name", String(length=255), nullable=False),
        Column("description", Text(), nullable=False),
        Column("created_at", DateTime(), nullable=False),
        Column("updated_at", DateTime(), nullable=False),
        PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_groups_name"), "groups", ["name"], unique=True)

    op.create_table(
        "permissions",
        Column("id", String(length=36), nullable=False),
        Column("resource_type", String(length=20), nullable=False),
        Column("resource_id", String(length=36), nullable=False),
        Column("grantee_type", String(length=10), nullable=False),
        Column("grantee_id", String(length=36), nullable=False),
        Column("capability", String(length=50), nullable=False),
        Column("mode", String(length=10), nullable=False),
        Column("created_at", DateTime(), nullable=False),
        PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_grantee", "permissions", ["grantee_type", "grantee_id"], unique=False)
    op.create_index("ix_resource", "permissions", ["resource_type", "resource_id"], unique=False)
    op.create_index(op.f("ix_permissions_grantee_id"), "permissions", ["grantee_id"], unique=False)
    op.create_index(
        op.f("ix_permissions_resource_id"), "permissions", ["resource_id"], unique=False
    )

    op.create_table(
        "sites",
        Column("id", String(length=36), nullable=False),
        Column("name", String(length=255), nullable=False),
        Column("content_url", String(length=255), nullable=False),
        Column("created_at", DateTime(), nullable=False),
        Column("updated_at", DateTime(), nullable=False),
        PrimaryKeyConstraint("id"),
        UniqueConstraint("name"),
    )
    op.create_index(op.f("ix_sites_content_url"), "sites", ["content_url"], unique=True)

    op.create_table(
        "users",
        Column("id", String(length=36), nullable=False),
        Column("name", String(length=255), nullable=False),
        Column("email", String(length=255), nullable=True),
        Column("site_role", String(length=50), nullable=False),
        Column("created_at", DateTime(), nullable=False),
        Column("updated_at", DateTime(), nullable=False),
        Column("site_id", String(length=36), nullable=False),
        PrimaryKeyConstraint("id"),
    )

    op.create_table(
        "group_users",
        Column("id", String(length=36), nullable=False),
        Column("group_id", String(length=36), nullable=False),
        Column("user_id", String(length=36), nullable=False),
        Column("created_at", DateTime(), nullable=False),
        ForeignKeyConstraint(
            ["group_id"],
            ["groups.id"],
        ),
        ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        PrimaryKeyConstraint("id"),
        UniqueConstraint("group_id", "user_id", name="unique_group_user"),
    )

    op.create_table(
        "projects",
        Column("id", String(length=36), nullable=False),
        Column("name", String(length=255), nullable=False),
        Column("description", Text(), nullable=False),
        Column("parent_project_id", String(length=36), nullable=True),
        Column("owner_id", String(length=36), nullable=False),
        Column("created_at", DateTime(), nullable=False),
        Column("updated_at", DateTime(), nullable=False),
        ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
        ),
        ForeignKeyConstraint(
            ["parent_project_id"],
            ["projects.id"],
        ),
        PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_projects_owner_id"), "projects", ["owner_id"], unique=False)
    op.create_index(
        op.f("ix_projects_parent_project_id"), "projects", ["parent_project_id"], unique=False
    )

    op.create_table(
        "datasources",
        Column("id", String(length=36), nullable=False),
        Column("name", String(length=255), nullable=False),
        Column("project_id", String(length=36), nullable=False),
        Column("owner_id", String(length=36), nullable=False),
        Column("connection_type", String(length=50), nullable=False),
        Column("description", Text(), nullable=False),
        Column("created_at", DateTime(), nullable=False),
        Column("updated_at", DateTime(), nullable=False),
        ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
        ),
        ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_datasources_owner_id"), "datasources", ["owner_id"], unique=False)
    op.create_index(op.f("ix_datasources_project_id"), "datasources", ["project_id"], unique=False)

    op.create_table(
        "workbooks",
        Column("id", String(length=36), nullable=False),
        Column("name", String(length=255), nullable=False),
        Column("project_id", String(length=36), nullable=False),
        Column("owner_id", String(length=36), nullable=False),
        Column("file_reference", String(length=500), nullable=True),
        Column("description", Text(), nullable=False),
        Column("created_at", DateTime(), nullable=False),
        Column("updated_at", DateTime(), nullable=False),
        ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
        ),
        ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_workbooks_owner_id"), "workbooks", ["owner_id"], unique=False)
    op.create_index(op.f("ix_workbooks_project_id"), "workbooks", ["project_id"], unique=False)

    op.create_table(
        "workbook_datasources",
        Column("id", String(length=36), nullable=False),
        Column("workbook_id", String(length=36), nullable=False),
        Column("datasource_id", String(length=36), nullable=False),
        Column("created_at", DateTime(), nullable=False),
        ForeignKeyConstraint(
            ["datasource_id"],
            ["datasources.id"],
        ),
        ForeignKeyConstraint(
            ["workbook_id"],
            ["workbooks.id"],
        ),
        PrimaryKeyConstraint("id"),
        UniqueConstraint("workbook_id", "datasource_id", name="unique_wb_ds"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("workbook_datasources")
    op.drop_index(op.f("ix_workbooks_project_id"), table_name="workbooks")
    op.drop_index(op.f("ix_workbooks_owner_id"), table_name="workbooks")
    op.drop_table("workbooks")
    op.drop_index(op.f("ix_datasources_project_id"), table_name="datasources")
    op.drop_index(op.f("ix_datasources_owner_id"), table_name="datasources")
    op.drop_table("datasources")
    op.drop_index(op.f("ix_projects_parent_project_id"), table_name="projects")
    op.drop_index(op.f("ix_projects_owner_id"), table_name="projects")
    op.drop_table("projects")
    op.drop_table("group_users")
    op.drop_table("users")
    op.drop_index(op.f("ix_sites_content_url"), table_name="sites")
    op.drop_table("sites")
    op.drop_index(op.f("ix_permissions_resource_id"), table_name="permissions")
    op.drop_index(op.f("ix_permissions_grantee_id"), table_name="permissions")
    op.drop_index("ix_resource", table_name="permissions")
    op.drop_index("ix_grantee", table_name="permissions")
    op.drop_table("permissions")
    op.drop_index(op.f("ix_groups_name"), table_name="groups")
    op.drop_table("groups")
    # ### end Alembic commands ###
